// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apcpaoivlcxgbfpomkhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwY3Bhb2l2bGN4Z2JmcG9ta2hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMTczMzYsImV4cCI6MjA2MTU5MzMzNn0.50DNfnJUMOzHNkyYLxWf3LYLXYbEs6enCGEbDtsY_Xo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);